DROP TABLE IF EXISTS review;

DROP TABLE IF EXISTS discounted_ticket;

DROP TABLE IF EXISTS ticket;

DROP TABLE IF EXISTS event_in_category;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS event;

DROP TABLE IF EXISTS venue;

DROP TABLE IF EXISTS area;

DROP TABLE IF EXISTS venue_type;

DROP TABLE IF EXISTS file;

DROP TABLE IF EXISTS guest;

DROP TABLE IF EXISTS organizer;

DROP TABLE IF EXISTS account;
