import "./globals.css";
import type { Metadata } from "next";
import { AxiomWebVitals } from "next-axiom";
import { Montserrat } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<AxiomWebVitals />
			<body className={montserrat.className}>
				{children}
				<Analytics />
			</body>
		</html>
	);
}
