import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { AxiomWebVitals } from "next-axiom";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		// TODO: ClerkProvider should only wrap pages that need authentication
		<ClerkProvider>
			<html lang="en">
				<AxiomWebVitals />
				<body className={inter.className}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
